---
# yamllint disable rule:line-length
name: Create Tag & Release
description: |
  This Action creates tags & release when merged to Master/Main.
  If tag/release already exists, then it is updated.

  ## Permissions

  Add the following permissions to the job

  ```yaml
  permissions:
    contents: write
  ```

  ## Usage

  ```yaml
  - name: Create Release Action
    uses: variant-inc/actions-collection/create-release-tag@v2
    env:
      RELEASE_FILES_GLOB: 'binaries/*' # Glob pattern for files to upload
    with:
      create_release: 'true'
  ```
inputs:
  create_release:
    description: Creates Release if true
    required: false
    default: 'true'
runs:
  using: composite
  steps:
    - name: Create or Update tags
      uses: actions/github-script@v8
      if: ${{ env.GitVersion_PreReleaseLabel == '' }}
      with:
        script: |
          const script = require('${{ github.action_path }}/tags.js')
          await script({github, context})
    - name: Create or Update Release
      uses: actions/github-script@v8
      if: ${{ env.GitVersion_PreReleaseLabel == '' && inputs.create_release == 'true' }}
      with:
        script: |
          const script = require('${{ github.action_path }}/release.js')
          await script({github, context})
    - name: Upload binaries to release
      uses: svenstaro/upload-release-action@v2
      if: ${{ env.RELEASE_FILES_GLOB != '' && env.GitVersion_PreReleaseLabel == '' && inputs.create_release == 'true' }}
      with:
        repo_token: ${{ env.GITHUB_TOKEN }}
        file: ${{ env.RELEASE_FILES_GLOB }}
        tag: v${{ env.GitVersion_MajorMinorPatch }}
        overwrite: true
        file_glob: true
