---
# yamllint disable rule:line-length
name: Create Tag & Release
description: |
  This Action creates tags & release when merged to Master/Main.
  If tag/release already exists, then it is updated.
inputs:
  create_release:
    description: Creates Release if true
    default: 'True'
runs:
  using: composite
  steps:
    - name: Create or Update tags
      uses: actions/github-script@v6
      if: ${{ env.GITVERSION_PRERELEASETAG != '' && env.GITVERSION_PRERELEASELABEL == '' }}
      with:
        script: |
          const script = require('${{ github.action_path }}/tags.js')
          await script({github, context})
    - name: Create or Update Release
      uses: actions/github-script@v6
      if: ${{ env.GITVERSION_PRERELEASETAG != '' && env.GITVERSION_PRERELEASELABEL == '' && inputs.create_release == 'True' }}
      with:
        script: |
          const script = require('${{ github.action_path }}/release.js')
          await script({github, context})
